"""Lifecycle finalization helpers for orchestration flows."""

from .completion import TaskCompletionFinalizer
from .worker_bootstrap import (
    build_claimed_details,
    build_identity_snapshot,
    env_value,
    run_start_config_snapshot,
    run_start_runtime_identity,
    should_use_configured_planning_runtime,
)
from .worker_capacity import (
    BACKEND_CAPACITY_RETRY_MAX_RETRIES,
    backend_capacity_retry_state,
    prepare_backend_capacity_retry,
)
from .transitions import (
    MAX_ACTIVE_LOGICAL_EXECUTIONS_PER_SESSION,
    VALID_CONTINUATION_KINDS,
    ContinuationIdentity,
    LifecycleTransitionError,
    TransitionResult,
    admit_autonomous_execution,
    admit_fresh_logical_execution,
    autonomous_continuation_owns_generation,
    begin_new_generation,
    claim_continuation,
    enter_recovering,
    finalize_logical_failure,
    finalize_logical_success,
    revoke_autonomous_continuation,
    schedule_continuation,
    start_new_generation,
    validate_continuation,
)

__all__ = [
    "TaskCompletionFinalizer",
    "build_claimed_details",
    "build_identity_snapshot",
    "env_value",
    "run_start_config_snapshot",
    "run_start_runtime_identity",
    "should_use_configured_planning_runtime",
    "BACKEND_CAPACITY_RETRY_MAX_RETRIES",
    "backend_capacity_retry_state",
    "prepare_backend_capacity_retry",
    "MAX_ACTIVE_LOGICAL_EXECUTIONS_PER_SESSION",
    "VALID_CONTINUATION_KINDS",
    "ContinuationIdentity",
    "LifecycleTransitionError",
    "TransitionResult",
    "admit_autonomous_execution",
    "admit_fresh_logical_execution",
    "autonomous_continuation_owns_generation",
    "begin_new_generation",
    "claim_continuation",
    "enter_recovering",
    "finalize_logical_failure",
    "finalize_logical_success",
    "revoke_autonomous_continuation",
    "schedule_continuation",
    "start_new_generation",
    "validate_continuation",
]
