"""Production grounding contracts, deterministic executor, and coordinator.

The coordinator remains provider-injected and is selected by a default-off
Planning boundary.  The executor remains provider-neutral and read-only.
"""

from .contracts import (
    EnclosingSymbolLocator,
    GroundingAction,
    GroundingActionKind,
    GroundingBudgetAccounting,
    GroundingBudgetDelta,
    GroundingBudgetLimits,
    GroundingBudgetSnapshot,
    GroundingExecutionError,
    GroundingObservation,
    GroundingOutcome,
    GroundingRequest,
    GroundingRequestRejection,
    GroundingSearchHit,
    InspectFileAction,
    MountedRouteLocator,
    ObservationProvenance,
    RequestProvenance,
    ResolveStructureAction,
    SearchTextAction,
    StructuralIdentity,
    StructuralRelation,
    SymbolDefinitionLocator,
    parse_grounding_request,
)
from .executor import GroundingExecutor
from .coordinator import (
    GroundingCoordinator,
    GroundingDecisionProvider,
    GroundingProviderError,
    render_grounding_state,
)
from .coordinator_contracts import (
    GroundingAssessment,
    GroundingAssessmentKind,
    GroundingCoordinatorState,
    GroundingDecisionContext,
    GroundingEvidence,
    GroundingProposal,
    GroundingRequestStateSignal,
    GroundingRequestStateSignalKind,
    GroundingResult,
    GroundingRunConfig,
    GroundingStateProjection,
    GroundingTaskReference,
    GroundingTerminalReason,
)
from .context_adapter import (
    apply_grounding_result_to_planning_context,
    render_grounding_result_context,
)

__all__ = [
    "EnclosingSymbolLocator",
    "GroundingAction",
    "GroundingActionKind",
    "GroundingBudgetAccounting",
    "GroundingBudgetDelta",
    "GroundingBudgetLimits",
    "GroundingBudgetSnapshot",
    "GroundingExecutionError",
    "GroundingExecutor",
    "GroundingCoordinator",
    "GroundingDecisionProvider",
    "GroundingProviderError",
    "GroundingAssessment",
    "GroundingAssessmentKind",
    "GroundingCoordinatorState",
    "GroundingDecisionContext",
    "GroundingEvidence",
    "GroundingProposal",
    "GroundingRequestStateSignal",
    "GroundingRequestStateSignalKind",
    "GroundingResult",
    "GroundingRunConfig",
    "GroundingStateProjection",
    "GroundingTaskReference",
    "GroundingTerminalReason",
    "apply_grounding_result_to_planning_context",
    "render_grounding_result_context",
    "render_grounding_state",
    "GroundingObservation",
    "GroundingOutcome",
    "GroundingRequest",
    "GroundingRequestRejection",
    "GroundingSearchHit",
    "InspectFileAction",
    "MountedRouteLocator",
    "ObservationProvenance",
    "RequestProvenance",
    "ResolveStructureAction",
    "SearchTextAction",
    "StructuralIdentity",
    "StructuralRelation",
    "SymbolDefinitionLocator",
    "parse_grounding_request",
]
